---
- name: 'Install and configure a Samba fileserver'
  hosts: 'samba_server'
  gather_facts: true
  become: true

  tasks:

    - name: 'Install the samba server packages'
      ansible.builtin.package:
        name:
          - 'samba'
          - 'samba-doc'
          - 'samba-client'
        state: 'present'

    - name: 'Create a directory /srv/samba-vagrant-libvirt/'
      ansible.builtin.file:
        path: '/srv/samba-vagrant-libvirt/'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: 'Create directories for each user in /srv/samba-vagrant-libvirt/'
      ansible.builtin.file:
        path: "/srv/samba-vagrant-libvirt/{{ item }}"
        state: 'directory'
        owner: "{{ item }}"
        group: 'samba-vagrant-libvirt'
        mode: '0700'
      loop:
        - 'testuser1'
        - 'testuser2'
        - 'testuser3'

    - name: 'Create the smb.conf'
      ansible.builtin.template:
        src: 'smb.conf.j2'
        dest: '/etc/samba/smb.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
        validate: testparm -s %s
      notify:
        - 'Restart the samba service'

    - name: 'Start and enable the samba service'
      ansible.builtin.service:
        name: 'smb.service'
        state: 'started'
        enabled: true

    #
    # https://stackoverflow.com/questions/44762488/non-interactive-samba-user-creation-via-ansible
    #
    - name: 'Create the samba users'
      ansible.builtin.shell: >
        (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
        || (echo '{{ item.password }}'; echo '{{ item.password }}')
        | smbpasswd -s -a {{ item.username }}
      register: create_samba_users
      changed_when: "'Added user' in create_samba_users.stdout"
      loop:
        - username: 'testuser1'
          password: 'testuser1'
        - username: 'testuser2'
          password: 'testuser2'
        - username: 'testuser3'
          password: 'testuser3'
      loop_control:
        label: "{{ item.username }}"

    - name: shell - set samba passwords correctly
      ansible.builtin.shell: >
        (smbclient -U {{ item.username }}%{{ item.password }} -L 127.0.0.1 2>&1 > /dev/null)
        || (echo '{{ item.password }}'; echo '{{ item.password }}')
        | smbpasswd {{ item.username }}
      register: verify_samba_users
      changed_when: "'New SMB password' in verify_samba_users.stdout"
      loop:
        - username: 'testuser1'
          password: 'testuser1'
        - username: 'testuser2'
          password: 'testuser2'
        - username: 'testuser3'
          password: 'testuser3'
      loop_control:
        label: "{{ item.username }}"

  handlers:

    - name: 'Restart the samba service'
      ansible.builtin.service:
        name: 'smb.service'
        state: 'restarted'
